### ISSUE TITLE
Error in U3-M5 notebook

### ISSUE THREAD

**Issue by BillStrait** [DJCordhose/deep-learning-crash-course-notebooks#2]
I haven't finished the module yet but

`X = df.as_matrix()` throws an error `X = df.as_matrix()`

`X = df.to_numpy()` seems to work.

**Comment by DJCordhose** [comment]
thanks for reporting, this has been fixed in this and the following notebooks

It might be worth checking out the notebooks converted to the more recent 2.x version of TensorFlow you can find here

https://github.com/DJCordhose/deep-learning-crash-course-notebooks#tensorflow-2
